version: "3.8"

services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - ./uploads:/app/public/uploads  # persist uploads
    environment:
      DATABASE_CLIENT: sqlite
      NODE_ENV: production
