version: "3.8"

services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    volumes:
      - /home/root/cms-base/strapi-uploads:/app/public/uploads    # Persist uploads
      - /home/root/cms-base/strapi-data:/app/.tmp/database        # Persist SQLite DB
    environment:
      DATABASE_CLIENT: sqlite
      NODE_ENV: production