
name: Build and Deploy Strapi

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t strapi-app .

      - name: Save Docker image to tarball
        run: docker save strapi-app -o strapi-app.tar

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "strapi-app.tar"
          target: "/home/${{ secrets.VPS_USER }}/"

      - name: SSH into VPS and run container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker load -i /home/${{ secrets.VPS_USER }}/strapi-app.tar
            docker stop strapi || true
            docker rm strapi || true
            docker run -d \
              --name strapi \
              -p 1337:1337 \
              -v /home/${{ secrets.VPS_USER }}/cms-base/strapi-uploads:/app/public/uploads \
              -v /home/${{ secrets.VPS_USER }}/cms-base/strapi-db:/app/.tmp \
              -e APP_KEYS="${{ secrets.STRAPI_APP_KEYS }}" \
              -e ADMIN_JWT_SECRET="${{ secrets.ADMIN_JWT_SECRET }}" \
              -e API_TOKEN_SALT="${{ secrets.API_TOKEN_SALT }}" \
              -e TRANSFER_TOKEN_SALT="${{ secrets.TRANSFER_TOKEN_SALT }}" \
              -e ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
              strapi-app